"use client";

import Link from "next/link";
import PageHero from "@/components/PageHero";
import { useCart } from "@/components/CartProvider";

export default function CartPage() {
  const { items, subtotal, updateQuantity, removeItem } = useCart();
  return <><PageHero title="Your Cart" breadcrumb="Cart" /><section className="px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-4xl">{items.length === 0 ? <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center dark:border-slate-700 dark:bg-slate-900/50"><p className="text-slate-600 dark:text-slate-300">Your cart is empty.</p><Link href="/products" className="mt-5 inline-flex rounded-full bg-brand-600 px-5 py-2.5 text-sm font-semibold text-white">Browse products</Link></div> : <div className="space-y-4">{items.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900/50"><div><h2 className="font-semibold text-slate-900 dark:text-white">{item.name}</h2><p className="text-sm text-slate-500">K {item.price.toLocaleString()} each</p></div><div className="flex items-center gap-3"><input aria-label={`Quantity for ${item.name}`} type="number" min="1" value={item.quantity} onChange={(event) => updateQuantity(item.id, Number(event.target.value))} className="w-20 rounded-lg border border-slate-300 px-2 py-2 text-sm dark:border-slate-700 dark:bg-slate-800 dark:text-white" /><span className="font-semibold text-slate-900 dark:text-white">K {(item.price * item.quantity).toLocaleString()}</span><button onClick={() => removeItem(item.id)} className="text-sm font-semibold text-red-600">Remove</button></div></div>)}<div className="flex items-center justify-between border-t border-slate-200 pt-5 dark:border-slate-700"><span className="font-semibold text-slate-900 dark:text-white">Subtotal</span><span className="text-xl font-bold text-slate-900 dark:text-white">K {subtotal.toLocaleString()}</span></div><div className="flex flex-wrap gap-3"><Link href="/checkout" className="inline-flex rounded-full bg-brand-600 px-6 py-3 text-sm font-semibold text-white">Continue to checkout</Link><Link href="/quote" className="inline-flex rounded-full border border-brand-300 px-6 py-3 text-sm font-semibold text-brand-700 hover:bg-brand-50 dark:border-brand-700 dark:text-brand-200 dark:hover:bg-brand-950/50">Request a quotation</Link></div></div>}</div></section></>;
}