"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { useCart } from "@/components/CartProvider";

export default function QuotePage() {
  const { items, subtotal } = useCart();
  const [details, setDetails] = useState({ name: "", email: "", phone: "", company: "" });
  const [ready, setReady] = useState(false);
  const [quoteNumber, setQuoteNumber] = useState("");

  if (items.length === 0 && !ready) {
    return <main className="mx-auto w-full max-w-3xl px-4 py-16 text-center sm:px-6"><h1 className="text-2xl font-bold text-slate-900 dark:text-white">Your cart is empty</h1><p className="mt-2 text-slate-600 dark:text-slate-300">Add products before requesting a quotation.</p><Link href="/products" className="mt-6 inline-flex rounded-full bg-brand-600 px-5 py-2.5 text-sm font-semibold text-white">Browse products</Link></main>;
  }

  if (!ready) {
    return <main className="mx-auto w-full max-w-2xl px-4 py-16 sm:px-6"><p className="text-sm font-semibold uppercase tracking-wide text-brand-600">Quotation request</p><h1 className="mt-2 text-3xl font-bold text-slate-900 dark:text-white">Prepare your product quotation</h1><p className="mt-3 text-sm text-slate-600 dark:text-slate-300">Enter your details and we will prepare a quotation for the products in your cart.</p><form onSubmit={(event) => { event.preventDefault(); setQuoteNumber(`KQ-${new Date().getFullYear()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`); setReady(true); }} className="mt-8 space-y-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-700 dark:bg-slate-900/50"><label className="block text-sm font-medium">Full name<input required value={details.name} onChange={(event) => setDetails({ ...details, name: event.target.value })} className="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-600 dark:bg-slate-800 dark:text-white" /></label><label className="block text-sm font-medium">Company (optional)<input value={details.company} onChange={(event) => setDetails({ ...details, company: event.target.value })} className="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-600 dark:bg-slate-800 dark:text-white" /></label><label className="block text-sm font-medium">Email<input required type="email" value={details.email} onChange={(event) => setDetails({ ...details, email: event.target.value })} className="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-600 dark:bg-slate-800 dark:text-white" /></label><label className="block text-sm font-medium">Phone<input required value={details.phone} onChange={(event) => setDetails({ ...details, phone: event.target.value })} className="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-600 dark:bg-slate-800 dark:text-white" /></label><button className="w-full rounded-full bg-brand-600 px-6 py-3 text-sm font-semibold text-white">Generate quotation</button></form></main>;
  }

  return <main className="quote-page mx-auto w-full max-w-4xl px-4 py-10 sm:px-6"><div className="quote-sheet bg-white p-8 text-slate-900 shadow-sm"><header className="quote-header flex items-start justify-between gap-6 border-b-2 border-brand-600 pb-6"><Image src="/logo-m.png" alt="Kelson Innovations" width={190} height={58} className="h-12 w-auto object-contain" /><div className="text-right text-sm"><p className="text-xl font-bold tracking-wide text-brand-700">QUOTATION</p><p className="mt-2 text-xs font-semibold uppercase tracking-wide text-slate-500">Quote no.</p><p className="font-semibold">{quoteNumber}</p><p className="mt-1 text-xs text-slate-500">Issued {new Date().toLocaleDateString()}</p></div></header><div className="mt-8 grid gap-8 text-sm sm:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Prepared for</p><p className="mt-2 font-semibold">{details.name}</p>{details.company && <p>{details.company}</p>}<p className="text-slate-600">{details.email}</p><p className="text-slate-600">{details.phone}</p></div><div className="sm:text-right"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Issued by</p><p className="mt-2 font-semibold">Kelson Innovations</p><p className="text-slate-600">IT Solutions & Managed Services</p><p className="text-slate-600">info@kelson.co.zm</p></div></div><table className="mt-10 w-full text-left text-sm"><thead><tr className="border-b-2 border-slate-300 text-xs uppercase tracking-wide text-slate-500"><th className="py-3">Description</th><th className="py-3 text-center">Qty</th><th className="py-3 text-right">Unit price</th><th className="py-3 text-right">Amount</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-b border-slate-200"><td className="py-4 font-medium">{item.name}</td><td className="py-4 text-center">{item.quantity}</td><td className="py-4 text-right">K {item.price.toLocaleString()}</td><td className="py-4 text-right font-medium">K {(item.price * item.quantity).toLocaleString()}</td></tr>)}</tbody><tfoot><tr><td colSpan={3} className="pt-6 text-right text-sm font-bold">Estimated total</td><td className="pt-6 text-right text-xl font-bold text-brand-700">K {subtotal.toLocaleString()}</td></tr></tfoot></table><div className="mt-14 grid gap-6 border-t border-slate-200 pt-5 text-xs text-slate-500 sm:grid-cols-2"><p>Quotation validity: 30 days from issue date.</p><p className="sm:text-right">Prices are subject to availability and final confirmation.</p></div></div><div className="mt-6 flex flex-wrap gap-3 print:hidden"><button type="button" onClick={() => window.print()} className="rounded-full bg-brand-600 px-5 py-2.5 text-sm font-semibold text-white">Print / Save as PDF</button><Link href="/cart" className="rounded-full border border-slate-300 px-5 py-2.5 text-sm font-semibold text-slate-700 dark:border-slate-600 dark:text-slate-200">Back to cart</Link></div></main>;
}
